### ISSUE TITLE
Which files you have modified？

### ISSUE THREAD

**Issue by gushu333** [Victorwz/zs-nmt-dae#1]
Hi, I enjoy your work. Can you tell me which files you have modified to implement your method?

**Comment by Victorwz** [comment]
For only reproducing our method, you can ignore installing the modified FairSeq. Instead, you can directly install FairSeq via ``pip install fairseq==0.10.1``. The modified files are intended for implementing some baselines, including MNMT-RS and Language Model Pre-training. The modified files are located in "fairseq/models/transformer.py", "fairseq/modulss/transformer_layer.py".

**Comment by gushu333** [comment]
OK, I understand. Thank you.
